server:
  port: 7999
spring:
  config:
    import: vault://
  cloud:
    bootstrap:
      enabled: true
  application:
   name: jpm-user-service
  aop:
    auto: true
  mvc:
    async:
      request-timeout: 30000
  data:
    mongodb:
      uri: mongodb://${db-user}:${db-password}@${domain}/${db-name}?authSource=${db-name}&retryWrites=true&w=majority
