server:
  port: 7999
spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: myroot
      kv:
        enabled: true
        backend: secret
        application-name: dev/user-service/mongodb
      fail-fast: true
  application:
   name: jpm-user-service
  aop:
    auto: true
  mvc:
    async:
      request-timeout: 30000
  data:
    mongodb:
      uri: mongodb://${db-user}:${db-password}@${domain}/${db-name}?authSource=${db-name}&retryWrites=true&w=majority
