server:
  port: 7999
spring:
  application:
   name: jpm-user-service
  aop:
    auto: true
  mvc:
    async:
      request-timeout: 30000
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/mongodb