server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: spc-api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: jpm-client-service
          uri: lb://jpm-client-service
          predicates:
            - Path=/client/**
#        - id: department-service
#          uri: lb://department-service
#          predicates:
#            - Path=/department/**