name: Project CI-CD
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile
      - pom.xml
      - .github/workflows/**
jobs:
  spc-service-registry-build:
    name: Build spc-service-registry
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'spc-service-registry/') || contains(github.event.head_commit.modified, 'spc-service-registry/')
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Service A
        working-directory: ./service-a
        run: mvn -B clean verify

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn clean install
    - name: Build and push the docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: girishtechieguy/jpm-advisory-service
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}