name: Multi-Module CI/CD

on:
  push:
    branches: [ main, master ]  # Added both common branch names
    paths:
      - 'spc-service-registry/**'
      - 'spc-config-server/**'
      - 'pom.xml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'spc-service-registry/**'
      - 'spc-config-server/**'
      - 'pom.xml'
      - '.github/workflows/**'

jobs:
  spc-service-registry:
    name: Build spc-service-registry
    if: |
      contains(github.event.head_commit.modified, 'spc-service-registry/') ||
      contains(github.event.head_commit.added, 'spc-service-registry/') ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven

      - name: Build
        working-directory: ./spc-service-registry
        run: mvn clean install

  spc-config-server:
    name: Build spc-config-server
    if: |
      contains(github.event.head_commit.modified, 'spc-config-server/') ||
      contains(github.event.head_commit.added, 'spc-config-server/') ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven

      - name: Build
        working-directory: ./spc-config-server
        run: mvn clean install